#!/usr/bin/env bash
# Auto-generated by fromscratch — production boot for a published Medusa store.
# Single-container runtime: Postgres + Redis + the Medusa engine (:9000) + the
# Next.js storefront (:8000, the published Service port). Mirrors the sandbox
# boot so what you saw in the preview is what ships.
#
# Trade-off (MVP): Postgres runs on the container's ephemeral disk, seeded from
# the sandbox snapshot (.fromscratch/medusa-db.sql.gz). Visitor-side data (new
# orders, signups) is lost on pod restart. For a real shop, point DATABASE_URL /
# REDIS_URL at managed Postgres + Redis.
set -e

PGDATA=/var/lib/postgresql/data
PGBIN=$(ls -d /usr/lib/postgresql/*/bin | sort -V | tail -1)
mkdir -p "$PGDATA" /run/postgresql
chown -R postgres:postgres "$PGDATA" /run/postgresql
if [ ! -f "$PGDATA/PG_VERSION" ]; then
  su postgres -c "$PGBIN/initdb -D $PGDATA -A trust -U postgres" >/dev/null 2>&1
fi
su postgres -c "$PGBIN/pg_ctl -D $PGDATA -o '-c listen_addresses=127.0.0.1 -p 5432' -w -t 60 start"
su postgres -c "psql -h 127.0.0.1 -U postgres -tc \"SELECT 1 FROM pg_database WHERE datname='medusa'\" | grep -q 1 || psql -h 127.0.0.1 -U postgres -c 'CREATE DATABASE medusa'"
redis-server --daemonize yes --bind 127.0.0.1 --port 6379 >/dev/null 2>&1 || true

ORIGIN="${PREVIEW_SCHEME:-https}://${PUBLIC_HOST}"
# Public admin origin (its own sub-host). The admin SPA must call THIS, not
# localhost, or it gets "Failed to fetch". CORS must include both origins.
ADMIN_ORIGIN="${FS_ADMIN_ORIGIN:-}"
ADMIN_BACKEND_URL="${ADMIN_ORIGIN:-http://localhost:9000}"
CORS_LIST="${ORIGIN}"
[ -n "$ADMIN_ORIGIN" ] && CORS_LIST="${ORIGIN},${ADMIN_ORIGIN}"

# --- backend env ---
cd /app/backend
cat > .env <<EOF
DATABASE_URL=postgres://postgres@127.0.0.1:5432/medusa
REDIS_URL=redis://127.0.0.1:6379
STORE_CORS=${ORIGIN}
ADMIN_CORS=${CORS_LIST}
AUTH_CORS=${CORS_LIST}
JWT_SECRET=${JWT_SECRET:-fromscratch-jwt-secret}
COOKIE_SECRET=${COOKIE_SECRET:-fromscratch-cookie-secret}
MEDUSA_BACKEND_URL=${ADMIN_BACKEND_URL}
EOF

# restore the sandbox snapshot once, else just migrate
if [ -f /app/.fromscratch/medusa-db.sql.gz ] && [ ! -f /app/.fromscratch/.prod-restored ]; then
  echo "medusa(prod): restoring sandbox DB snapshot…"
  gunzip -c /app/.fromscratch/medusa-db.sql.gz | psql -h 127.0.0.1 -U postgres medusa || true
  touch /app/.fromscratch/.prod-restored
else
  npx --yes medusa db:migrate || true
fi

# --- Medusa engine on :9000 (PRODUCTION, not dev) ---
# A published store must NOT run `medusa develop`: that serves the admin via a
# Vite dev server, and Medusa hardcodes `<script src="/app/@vite/client">` in the
# admin HTML. That client opens an HMR websocket on :24678 — a port Traefik can't
# route — so the admin endlessly retries (waitForSuccessfulPing) and never loads.
# Build the admin into a static bundle once, then `medusa start` serves it at
# /app with no Vite and no HMR. This is also the correct production setup.
cd /app/backend
if [ ! -d /app/backend/.medusa/server ]; then
  echo "medusa(prod): building server + admin (first boot)…"
  NODE_ENV=production npx --yes medusa build || true
fi
( NODE_ENV=production npx --yes medusa start ) &
for i in $(seq 1 300); do curl -fsS http://localhost:9000/health >/dev/null 2>&1 && break; sleep 1; done

# Give this published store a UNIQUE admin password (the snapshot ships the
# default admin@medusa.local). Drop the seeded admin + its auth identities, then
# recreate with the per-store password. Best effort: on any hiccup the default
# admin stays (still reachable), so boot never fails on this.
if [ -n "$FS_ADMIN_PASSWORD" ]; then
  psql -h 127.0.0.1 -U postgres medusa >/dev/null 2>&1 <<'SQL' || true
DELETE FROM provider_identity WHERE entity_id = 'admin@medusa.local';
DELETE FROM auth_identity WHERE id NOT IN (SELECT auth_identity_id FROM provider_identity);
DELETE FROM "user" WHERE email = 'admin@medusa.local';
SQL
  npx --yes medusa user -e admin@medusa.local -p "$FS_ADMIN_PASSWORD" >/dev/null 2>&1 || true
fi

# storefront publishable key (created by the seed, carried in the snapshot)
PUBKEY=$(psql -h 127.0.0.1 -U postgres -tA medusa -c "SELECT token FROM api_key WHERE type='publishable' ORDER BY created_at LIMIT 1" 2>/dev/null | tr -d '[:space:]')

# --- storefront env ---
cd /app/storefront
cat > .env.local <<EOF
MEDUSA_BACKEND_URL=http://localhost:9000
NEXT_PUBLIC_MEDUSA_BACKEND_URL=${ORIGIN}/_medusa
NEXT_PUBLIC_BASE_URL=${ORIGIN}
NEXT_PUBLIC_DEFAULT_REGION=us
NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=${PUBKEY}
REVALIDATE_SECRET=fromscratch-revalidate
EOF

# /_medusa/* → :9000 rewrite so the browser reaches the API on the single port
if ! grep -q "_medusa" next.config.js 2>/dev/null; then
  cat > next.config.fs.js <<'CFG'
const base = require("./next.config.base.js");
const rewrites = async () => {
  const extra = [{ source: "/_medusa/:path*", destination: "http://localhost:9000/:path*" }];
  const prev = typeof base.rewrites === "function" ? await base.rewrites() : (base.rewrites || []);
  return Array.isArray(prev) ? [...extra, ...prev] : { ...prev, beforeFiles: [...extra, ...(prev.beforeFiles || [])] };
};
module.exports = { ...base, rewrites };
CFG
  mv next.config.js next.config.base.js
  mv next.config.fs.js next.config.js
fi

# Next in webpack mode (turbopack can't resolve through the symlinked deps tree)
exec ./node_modules/.bin/next dev -p "${APP_PORT:-8000}" -H 0.0.0.0
